{{- $resourceDiscoveryGroups := toYaml .Values.resourceDiscoveryGroups -}}
{{- $subscriptionIds := toYaml .Values.azureLandscape.subscriptionIds -}}
{{- $subscriptions := toYaml .Values.azureLandscape.subscriptions -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map-{{ template "promitor-agent-resource-discovery.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promitor-agent-resource-discovery.labels" . | nindent 4 }}
data:
  runtime.yaml: |-
      server:
        httpPort: {{ .Values.service.targetPort | quote }}
      authentication:
        mode: {{ .Values.azureAuthentication.mode | default "ServicePrincipal"}}
  {{- if .Values.azureAuthentication.identity.id }}
        identityId: {{ .Values.azureAuthentication.identity.id}}
  {{- else if .Values.azureAuthentication.appId }}
        identityId: {{ .Values.azureAuthentication.appId}}
  {{- end }}
      cache:
        enabled: {{ .Values.cache.enabled | quote }}
        durationInMinutes: {{ .Values.cache.durationInMinutes | quote }}
      telemetry:
        applicationInsights:
  {{- if .Values.telemetry.applicationInsights.key }}
          instrumentationKey: {{ .Values.telemetry.applicationInsights.key | quote }}
  {{- end }}
          isEnabled: {{ .Values.telemetry.applicationInsights.enabled | quote }}
  {{- if .Values.telemetry.applicationInsights.logLevel }}
          verbosity: {{ .Values.telemetry.applicationInsights.logLevel | quote }}
  {{- end }}
        containerLogs:
          isEnabled: {{ .Values.telemetry.containerLogs.enabled | quote }}
  {{- if .Values.telemetry.containerLogs.logLevel  }}
          verbosity: {{ .Values.telemetry.containerLogs.logLevel | quote }}
  {{- end }}
        defaultVerbosity: {{ .Values.telemetry.defaultLogLevel | quote  }}
  resource-discovery-declaration.yaml: |-
    version: v1
    azureLandscape:
      tenantId: {{ .Values.azureLandscape.tenantId }}
      subscriptions:
  {{- if .Values.azureLandscape.subscriptionIds }}
{{ tpl $subscriptionIds . | indent 6 }}
  {{- end }}
  {{- if .Values.azureLandscape.subscriptions }}
{{ tpl $subscriptions . | indent 6 }}
  {{- end }}
      cloud: {{ .Values.azureLandscape.cloud }}
  {{- if .Values.azureLandscape.endpoints }}
      endpoints:
    {{- range $key, $value := .Values.azureLandscape.endpoints }}
        {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}  
    resourceDiscoveryGroups:
{{ tpl $resourceDiscoveryGroups . | indent 4 }}
